### ISSUE TITLE
Child controller presenter being detached when parent has RetainViewMode.RETAIN_DETACH

### ISSUE THREAD

**Issue by mradzinski** [sockeqwe/mosby-conductor#33] opened 2017-11-13 22:23 UTC
Hey @sockeqwe, I just noticed a very strange behavior where Mosby is not honoring the `retainViewMode` of a parent Conductor controller. 

I have 2 controllers (let's call it Parent and Child for simplicity), Parent has `RetainViewMode.RETAIN_DETACH` applied to it and Child is nested into it, so I was expecting Mosby not to call `detachView` on the Child controller presenter (it's not being called on Parent, so Child was expected to behave the same way) but to my surprise the `detachView` method of Child controller presenter is being called when pushing a new controller to the stack. I think this shouldn't be the behavior; Children (nested) controllers should honor parent controllers retain mode, so if a parent has `RetainViewMode.RETAIN_DETACH` children should not call `detachView` either. 

Furthermore `detachView` is only called once the first time the router pushes another controller, but when popping and pushing again its not not happening.

**Comment by sockeqwe** [comment] 2017-11-13 22:32
RetainViewMode.RETAIN_DETACH is not supported at all ... Simply not
implemented yet ...

Matias Radzinski <notifications@github.com> schrieb am Mo., 13. Nov. 2017,
23:23:

**Comment by mradzinski** [comment] 2017-11-13 22:37
That's indeed weird. I don't observe a presenters destruction on parent controllers with retainViewMode.RETAIN_DETACH, when in the lifecycle of a controller the presenter is being destroyed or detachView called?

**Comment by mradzinski** [comment] 2017-11-13 22:59
Check this logs. Parent has `RetainViewMode.RETAIN_DETACH` while Child doesn't:

```
E: Parent Presenter: Attached parent view... (attachView() method)
E: Child Presenter: Attached child view... (attachView() method)
E: Parent Controller: Pushing controller...
E: Child Presenter: Detaching child view... (detachView() method)
E: Back pressed... Back to Parent
E: Parent Controller: Pushing controller...
E: Back pressed... Back to Parent
E: Parent Controller: Pushing controller...
E: Back pressed... Back to Parent
E: Back pressed... Leaving Parent
E: Parent Presenter: Detaching parent view... (detachView() method)
```
The only thing I can think of is that the Parent's presenter isn't being detached due to its Controller having `RetainViewMode.RETAIN_DETACH`, that's why I was expecting the child to honor it as well. Furthermore, I was expecting at least to hit `Detaching child view... (detachView() method)` every time a controller was pushed and `Attached child view... (attachView() method)` whenever popping back to the parent.

I guess the only way to have a stable lifecycle is if both, parent AND child have `RetainViewMode.RETAIN_DETACH` set.

**Comment by dimsuz** [comment] 2017-11-14 17:28
Hi!

I think this might be related to the issue I had reported to the Conductor team: bluelinelabs/Conductor#314.
I did some research (see the second comment there) and found out that it has to do with behavior of child controllers in `RETAIN_DETACH` mode.
This was about controllers inside a ViewPager though, so not 100% sure it's your issue, but sound very similar.

**Comment by svkostadinoff** [comment] 2017-11-17 13:44
Another related issue https://github.com/bluelinelabs/Conductor/issues/277

**Comment by mradzinski** [comment] 2017-11-19 17:05
I think the main question (and I guess @sockeqwe will have to be the one to answer this one) is: 

Does an invokation to `detachView` on a presenter means that that presenter is considered to be destroyed and available for GC? If the answer is no then I believe presenters should have two separate methods, one for whenever the view is being detached (`detachView`) and one for when the presenter is no longer needed and hence ready for GC (`onDestroy`), that way Mosby is following Conductor's lifecycle, and as a counter-effect gains readability and an easier way of thinking of its presenter's lifecycle. If the answer to the question is yes (`detachView` means a presenter is available for GC) then `detachView` should honor the `RetainViewMode` of the Controller it's attached to and avoid calling `detachView` if its Controller (or any Controller above it in hierarchy, aka parents) has `RetainViewMode` set to `RETAIN_DETACH`.

Right now as it is we are forced to use `RetainViewMode.RETAIN_DETACH` on every controller we don't want the presenter's `detachView` to be invoked. This is due to the fact that on Mosby-Conductor `presenter.detachView` is being called during the `preDestroyView` method of Conductor's `LifecycleListener`.

**Comment by sockeqwe** [comment] 2017-11-19 19:47
Mosby 3.0.x has one method detachView(boolen retainsInstance). In other
words an invocation of detachView(false) means Presenter is goning to be
"destoryed" and can be garbage collected because the corresponding View is
destroyed permanently. detachView(true) means view is detached temporarily
i.e. screen orientation change or backstack navigation.

Starting in Mosby 3.1.0 there is one detachView() (no parameter) and
destroy(). Mosby 3.1.0 is not released yet, but will be released soon.

Matias Radzinski <notifications@github.com> schrieb am So., 19. Nov. 2017,
17:05:

**Comment by sockeqwe** [comment] 2017-11-19 20:01
What I meant with retain mode is not supported is that it may (or may not,
I never have tested / used Mosby with that retain mode) need internally
some changes regarding ViewController lifecycle events becaue they might be
different from what they are usually.  Anothwr qustion is:  android view
(Im talking about ui widgets, like FrameLayout) can be updated even if its
not attached to any activity / window (which is what that RetainMode does,
keep view in memory but detach it from activity/ window). So the question
is, should Mosby Presenter stay attached to the "MVP View" in that case too?

Hannes Dorfmann <hannes.dorfmann@gmail.com> schrieb am So., 19. Nov. 2017,
19:47:

**Comment by mradzinski** [comment] 2017-11-19 20:14
@sockeqwe, What happens to the presenter when the Conductor router pushes a new Controller to the backstack? I'm positive `detachView` is being called, but I actually added a constructor to one presenter (which happens to be attached to a controller without any `retainView` set to it) to realize if the presenter was being recreated upon going back to the previous controller (back button or router.popCurrentController, same thing) or being reused and I'm constantly seeing that the same instance of the presenter is there and being used (not collected, not destroyed, being reused). This behavior does not correlate to your statement that `detachView(false)` means the presenter is destroyed (would that be the case a new instance should've been created to avoid NPE's upon returning to a previous Controller). On Mosby-Conductor `presenter.detachView()` is being called during the Controllers `preDestroyView` life event, and I'm sure Conductor invokes this when pushing a new Controller to the backstack, but in that scenario it never invokes `onDestroy`, so if the presenter is being destroyed then there's a big bug there (unless you are checking and creating a new instance of the presenter if the same has been GC'ed).

In regards to your question: `Should Mosby Presenter stay attached to the "MVP View" in that case too?`: I would say "no", but its a matter of analyzing use cases and pros and cons.

**Comment by sockeqwe** [comment] 2017-11-20 14:21
The idea is that a presenter lives as long as the ViewController lives.

Example:
1. ViewControllerA is shown --> PresenterA.attachView()
2. push ViewControllerB on router: PresenterA.detachView(). ViewControllerB is shown --> PresenterB.attachView()
3. pop ViewController B from backstack. PresenterB.detachView() and PresenterB.destroy() (in Mosby 3.0.x it is just PresneterB.detachView(false) ) PresenterA.attachView() as ViewControllerA now comes to the foreground.

**Comment by mradzinski** [comment] 2017-11-20 15:21
So, I made a small test. None of this Controllers have any kind of retainMode set to them.

```
E: New Controller Pushed From A (Controller B)
E: Presenter B Constructor -> ...@59b7213
E: Presenter B attachView -> ...@59b7213
E: New Controller Pushed From B (Controller C)
E: Presenter B detachView(retainInstance = false) -> ...@59b7213
E: ---------------------------------------
E: Controller Popped (ControllerC)
E: Presenter B attachView -> ...@59b7213
E: New Controller Pushed From B (Controller C)
E: Presenter B detachView(retainInstance = false) -> ...@59b7213
E: ---------------------------------------
E: New Controller Pushed From C (Controller D)
E: New Controller Pushed From D (Controller E)
E: Controller Popped (Controller E)
E: Controller Popped (Controller D)
E: Controller Popped (Controller C)
E: Presenter B attachView -> ...@59b7213
E: Controller Hit onDestroy (Controller B)
E: Presenter B detachView(retainInstance = false) -> ...@59b7213
E: ---------------------------------------
E: New Controller Pushed From A (Controller B)
E: Presenter B Constructor -> ...@6bb3651
E: Presenter B attachView -> ...@6bb3651
```

Check the instances of the presenter attached to Controller B. Presenter B isn't being recreated, it has the same instance regardless of how many controllers you push on top of Controller B (so its being reused?). However `detachView` is always called with `retainInstance = false` and the presenter It's only being re-created whenever the Controller hits `onDestroy` (its being popped from the backstack).

This logcat output matches exactly with how Conductor treats Controllers. A Controller reference is disposed whenever the Controller hits `onDestroy` which is not executed at all when a new controller is push to the stack. So AFAIK, `detachView(true)` should be called whenever the controller detaches its view (`onViewDestroyed`), and `detachView(false)` when the controller hits `onDestroy` (is being popped from the backstack) since the instance isn't being retained anymore.

**Comment by sockeqwe** [comment] 2017-11-28 19:24
Ok, so let's see, with Mosby 3.1.0 (Presenter.destroy() instead of Presenter.detachView(boolean)) the logs on my sample app looks like this for a simple application where I put Controller1 on the backstack and then Controller2, then back press button so that controller2 is removed and Controller 1 is visible again (code can be found [here](https://github.com/sockeqwe/mosby-conductor/tree/master/integrationtest).

```
 1. App Starts   
       MvpTestController    Controller1.onCreateView()
       MvpTestPresenter    Presenter1.attachView()


2. Push Controller2 on the backstack  
      MvpTestController    Controller2.onCreateView()
       MvpTestPresenter    Presenter2.attachView()
                           Presenter1.detachView()
      MvpTestController    Controller1.onDestroyView()


3. Press Back button (pop backstack)
      MvpTestController    Controller1.onCreateView()
       MvpTestPresenter    Presenter1.attachView()
                           Presenter2.detachView()
      MvpTestController    Controller2.onDestroyView()
                           Controller2.onDestroy()
       MvpTestPresenter    Presenter2.destroy()



4. Press Back button (exit activity / application)
       MvpTestPresenter    Presenter1.detachView()
      MvpTestController    Controller1.onDestroyView()
                           Controller1.onDestroy()
       MvpTestPresenter    Presenter1.destroy()
```


So if I do the same with `RETAIN_DETACH` I get the following output:

```
1. App starts
      MvpTestController    Controller1.onCreateView()
       MvpTestPresenter    Presenter1.attachView()


2. Push Controller2 on the backstack 
      MvpTestController    Controller2.onCreateView()
       MvpTestPresenter    Presenter2.attachView()


3. Press Back button (pop backstack)
       MvpTestPresenter    Presenter2.detachView()
      MvpTestController    Controller2.onDestroyView()
                           Controller2.onDestroy()
       MvpTestPresenter    Presenter2.destroy()


4. Press Back button (exit activity / application)
       MvpTestPresenter    Presenter1.detachView()
      MvpTestController    Controller1.onDestroyView()
                           Controller1.onDestroy()
```


So this looks pretty good and working as intended to me for both RETAIN modes.

Please note that View of Presenter1 is not detached from Presenter1 on purpose in  RETAIN_DETACH because view can still be updated although view is not visible.

As said before, Conductor itself may have an issue with RETAIN mode and child controllers and how the view reference is kept.

**Closed as completed by sockeqwe** 2017-11-28 19:24 UTC
