### ISSUE TITLE
Conductor v2 (RC) NullPointerException

### ISSUE THREAD

**Issue by leonardo2204** [sockeqwe/mosby-conductor#2] opened 2016-06-18 00:06 UTC
After using child Routers in my app I'm facing a strange behavior:

```
06-17 21:03:41.184 2717-2717/com.chaseapp.chaseapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.chaseapp.chaseapp, PID: 2717
                                                                     java.lang.RuntimeException: Unable to destroy activity {com.chaseapp.chaseapp/com.chaseapp.chaseapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.isChangingConfigurations()' on a null object reference
                                                                         at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3706)
                                                                         at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3724)
                                                                         at android.app.ActivityThread.access$1400(ActivityThread.java:151)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.isChangingConfigurations()' on a null object reference
                                                                         at com.hannesdorfmann.mosby.mvp.conductor.delegate.MvpConductorLifecycleListener.preDestroyView(MvpConductorLifecycleListener.java:74)
                                                                         at com.hannesdorfmann.mosby.conductor.viewstate.delegate.MvpViewStateConductorLifecycleListener.preDestroyView(MvpViewStateConductorLifecycleListener.java:44)
                                                                         at com.bluelinelabs.conductor.Controller.removeViewReference(Controller.java:811)
                                                                         at com.bluelinelabs.conductor.Controller.detach(Controller.java:800)
                                                                         at com.bluelinelabs.conductor.Controller.destroy(Controller.java:916)
                                                                         at com.bluelinelabs.conductor.Controller.activityDestroyed(Controller.java:750)
                                                                         at com.bluelinelabs.conductor.Router.onActivityDestroyed(Router.java:414)
                                                                         at com.bluelinelabs.conductor.ControllerHostedRouter.onActivityDestroyed(ControllerHostedRouter.java:68)
                                                                         at com.bluelinelabs.conductor.Router.onActivityDestroyed(Router.java:417)
                                                                         at com.bluelinelabs.conductor.ActivityHostedRouter.onActivityDestroyed(ActivityHostedRouter.java:40)
                                                                         at com.bluelinelabs.conductor.internal.LifecycleHandler.destroyRouters(LifecycleHandler.java:158)
                                                                         at com.bluelinelabs.conductor.internal.LifecycleHandler.onDestroy(LifecycleHandler.java:127)
                                                                         at android.app.Fragment.performDestroy(Fragment.java:2266)
                                                                         at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1017)
                                                                         at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                         at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1049)
                                                                         at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1897)
                                                                         at android.app.Activity.performDestroy(Activity.java:6168)
                                                                         at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1141)
                                                                         at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3693)
                                                                         at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3724) 
                                                                         at android.app.ActivityThread.access$1400(ActivityThread.java:151) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 

```

Using Conductor v2 RC3 and mosby-conductor 0.7

**Comment by ahmedrizwan** [comment] 2016-06-30 10:11
Facing the exact same issue, while using ControllerPagerAdapter. 
The exception gets thrown when I rotate the device (change configuration).

**Comment by chris6647** [comment] 2016-07-01 09:16
I also experience this problem. I'm using the OverlayController from the Conductor sample, converted to work with Mosby. It happens when the screen orientation is changed.
The issue seems to be due to all childRouters having their host removed (Controller:787), when that host gets the activityDestroyed callback (which is does, before the childRouters do), and the Mvp LifecycleListeners attempts to access the activity in order to check whether or not the configuration is changing.

`
07-01 11:06:42.306 29741-29741/com.demo.app.template.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.demo.app.template.debug, PID: 29741
                                                                               java.lang.RuntimeException: Unable to destroy activity {com.demo.app.template.debug/com.demo.app.template.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.isChangingConfigurations()' on a null object reference
                                                                                   at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3831)
                                                                                   at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
                                                                                   at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4053)
                                                                                   at android.app.ActivityThread.-wrap15(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.isChangingConfigurations()' on a null object reference
                                                                                   at com.hannesdorfmann.mosby.mvp.conductor.delegate.MvpConductorLifecycleListener.preDestroyView(MvpConductorLifecycleListener.java:74)
                                                                                   at com.hannesdorfmann.mosby.conductor.viewstate.delegate.MvpViewStateConductorLifecycleListener.preDestroyView(MvpViewStateConductorLifecycleListener.java:44)
                                                                                   at com.bluelinelabs.conductor.Controller.removeViewReference(Controller.java:773)
                                                                                   at com.bluelinelabs.conductor.Controller.detach(Controller.java:762)
                                                                                   at com.bluelinelabs.conductor.Controller.activityDestroyed(Controller.java:710)
                                                                                   at com.bluelinelabs.conductor.Router.onActivityDestroyed(Router.java:415)
                                                                                   at com.bluelinelabs.conductor.ControllerHostedRouter.onActivityDestroyed(ControllerHostedRouter.java:68)
                                                                                   at com.bluelinelabs.conductor.Router.onActivityDestroyed(Router.java:418)
                                                                                   at com.bluelinelabs.conductor.ActivityHostedRouter.onActivityDestroyed(ActivityHostedRouter.java:40)
                                                                                   at com.bluelinelabs.conductor.internal.LifecycleHandler.destroyRouters(LifecycleHandler.java:161)
                                                                                   at com.bluelinelabs.conductor.internal.LifecycleHandler.onDetach(LifecycleHandler.java:152)
                                                                                   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
                                                                                   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
                                                                                   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
                                                                                   at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1981)
                                                                                   at android.app.FragmentController.dispatchDestroy(FragmentController.java:218)
                                                                                   at android.app.Activity.performDestroy(Activity.java:6421)
                                                                                   at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
                                                                                   at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)
                                                                                   at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849) 
                                                                                   at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4053) 
                                                                                   at android.app.ActivityThread.-wrap15(ActivityThread.java) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

**Comment by sockeqwe** [comment] 2016-07-06 13:43
Sorry for the late response. Accidentally I have unwatched this repository and didn't get notifications.

So yes, I'm aware of this issue. From my point of view it is a conductor issue. I have already reported that:
https://github.com/bluelinelabs/Conductor/issues/85

I'm not sure if I can provide another workaround

**Comment by chris6647** [comment] 2016-07-06 13:45
I considered if i should have posted the bug report on Conductor too, but great you reported it there. Thanks :)

**Comment by leonardo2204** [comment] 2016-07-06 13:58
I debugged and came to the same conclusion. After I saw your Issue on Conductor, I realized that it might realy be a problem on Conductor side, not Mosby's.
Thanks again for the reply @sockeqwe

**Comment by sockeqwe** [comment] 2016-07-06 14:25
I think there is no workaround that will work in the mean time (until fixed in Conductor properly). Sorry ...

**Comment by sockeqwe** [comment] 2016-07-06 22:53
Ok, I have found a temporarily workaround. I have published a new version `0.8.0` of this library, containing this temporarily workaround. However, this issue should be fixed in conductor.

**Comment by chris6647** [comment] 2016-07-07 12:26
It doesnt seem to work completely though. While it prevents the crash, the OverlayController in the childRouter is removed upon device rotation. This also happened when i tried my own hacky-fix which was setting a custom LifecycleListener and when it got the preDestroy callback, it would loop through all children and manually call the preDestroy on all children (so they got the callback, before the hosting router was removed).

**Comment by sockeqwe** [comment] 2016-07-07 13:40
This is not an issue of this library. This an issue of Conductor himself (in my opinion). See https://github.com/bluelinelabs/Conductor/issues/86

The aim of this library is to work with Presenters. Attaching and detaching presenters is working as expected form my point of view this works with this "workaround", doesn't it?

**Closed as completed** 2016-07-08 09:24 UTC

**Comment by leonardo2204** [comment] 2016-07-08 13:44
@sockeqwe Thanks man !

**Comment by ZakTaccardi** [comment] 2016-09-11 23:50
New to mosby/conductor, but I am getting this issue :(

Versions below

```
mosby                     : '2.0.1',
mosbyConductor   : '0.8.2',
conductor               : '2.0.1',

```

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.isChangingConfigurations()' on a null object reference
                                                       at com.hannesdorfmann.mosby.mvp.conductor.delegate.MvpConductorLifecycleListener.preDestroyView(MvpConductorLifecycleListener.java:72)
                                                       at com.bluelinelabs.conductor.Controller.removeViewReference(Controller.java:776)
                                                       at com.bluelinelabs.conductor.Controller.detach(Controller.java:765)
                                                       at com.bluelinelabs.conductor.Controller$7.onViewDetachedFromWindow(Controller.java:834)
                                                       at android.view.View.dispatchDetachedFromWindow(View.java:14572)
                                                       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3071)
                                                       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                       at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3068)
                                                       at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5606)
                                                       at android.view.ViewRootImpl.die(ViewRootImpl.java:5583)
                                                       at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:397)
                                                       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:352)
                                                       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
                                                       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3867)
                                                       at android.app.ActivityThread.-wrap5(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by sockeqwe** [comment] 2016-09-12 08:46
Hi, I'm sorry!
I ve tried to reproduce this, but wasn't able. Is there any code snippet
you can share with me to reproduce this?

Zak Taccardi notifications@github.com schrieb am Mo., 12. Sep. 2016,
01:50:

**Comment by ZakTaccardi** [comment] 2016-09-12 08:48
I think I was doing weird stuff in how I constructed my presenters by using dagger to inject them.

**Comment by ZakTaccardi** [comment] 2016-09-12 08:49
Consider my issue closed ^^^

And thank you!

**Comment by deniszink** [comment] 2017-02-02 17:04
Hi, this exception appeared again

` compile 'com.hannesdorfmann.mosby:mvp-conductor:0.8.2'`
  ` compile 'com.bluelinelabs:conductor:2.0.7'`

` java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.isChangingConfigurations()' on a null object reference
                                                                                   at com.hannesdorfmann.mosby.mvp.conductor.delegate.MvpConductorLifecycleListener.preDestroyView(MvpConductorLifecycleListener.java:72)
                                                                                   at com.bluelinelabs.conductor.Controller.removeViewReference(Controller.java:846)
                                                                                   at com.bluelinelabs.conductor.Controller.detach(Controller.java:834)
                                                                                   at com.bluelinelabs.conductor.Controller$7.onDetached(Controller.java:915)
                                                                                   at com.bluelinelabs.conductor.internal.ViewAttachHandler$1.onViewDetachedFromWindow(ViewAttachHandler.java:45)
                                                                                   at android.view.View.dispatchDetachedFromWindow(View.java:14578)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3071)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
                                                                                `

**Comment by sockeqwe** [comment] 2017-02-02 17:08
Which version of conductor are you using? I think this  is caused
internally by conductor and should be fixed in conductor 2.1.0. please try
upgrade to 2.1.0 and retry it again

Denis Zinkovskiy <notifications@github.com> schrieb am Do., 2. Feb. 2017,
18:04:

**Comment by sockeqwe** [comment] 2017-02-02 17:09
Sorry,  I have overlooked that you have mentioned that you are using
2.0.7. please try to update to 2.1.0

Hannes Dorfmann <hannes.dorfmann@gmail.com> schrieb am Do., 2. Feb. 2017,
18:08:

**Comment by deniszink** [comment] 2017-02-02 17:19
@sockeqwe, thanks for quick reply, I have updated conductor, problem is gone
